#!/bin/bash
# set -x

# check to make sure grep comes back with something and there is more than 1 argument
if [ $# -gt 0 ]; then

	SUBCMD=$(grep "$1\s*\=" ~/.gitconfig | cut -d '=' -f 2-) # grab everything after the = of the alias 
	#(i.e. 'ls = list --apply' grabs the 'list --apply')
	
	if [$? -ne 0 ]; then
		exit 1
	fi

	# write out alias call if it is an alias
	if [ ! -z "$SUBCMD" ]; then
		SUBCMD_DISPLAY=$(sed 's/\\//g' <<< ${SUBCMD}) # remove escape characters
		echo "git $SUBCMD"
	fi
fi
#run git command
bash -c "git $SUBCMD_DISPLAY"


# test make this work with autocomplete. 
# i want git-show to autocomplete as git. 